global:
  scrape_interval:
    5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'metrics-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.17.0.1:8180']
    basic_auth:
      username: "user"
      password: "password"